main: de.typable.minecrafthub.Main
name: MinecraftHub
version: 0.0.1
author: typable
api-version: 1.16
commands:
  head:
  skull:
    usage: /skull <player>
  spawn:
    usage: /spawn
  invsee:
    usage: /invsee <name> <enderchest>
  sethome:
  home:
  setwarp:
    usage: /setwarp <name>
  warp:
    usage: /warp <name>
  info:
