main: poppy.Main
name: poppy
version: 0.1.0
author: typable, chunksize
api-version: 1.16
commands:
  head:
  skull:
    usage: /skull <player>
  spawn:
    usage: /spawn
  invsee:
    usage: /invsee <name>
  sethome:
  home:
  setwarp:
    usage: /setwarp <name>
  warp:
    usage: /warp <name>
  slime:
    usage: /slime
  r:
    usage: /r
  up:
    usage: /up
  info:
